all: getversion mkversionpl makeinstall perlpp

getversion: /map/getversion/bin/getversion
	cp $< $@

mkversionpl: /map/getversion/bin/mkversionpl
	cp $< $@

makeinstall: /map/makeinstall/bin/makeinstall
	cp $< $@

perlpp: /map/perlpp/bin/perlpp
	cp $< $@
